name: hostnstore_mobile
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  stacked: ^3.4.3
  stacked_services: ^1.5.1
  google_fonts: ^6.2.1
  device_preview: ^1.2.0
  image_editor_plus: ^1.0.6
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutterbackgroundremover: ^0.0.1
  dio: ^5.7.0
  fluttertoast: ^8.2.8
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  motion_toast: ^2.11.0
  flutter_secure_storage: ^9.2.0
  intl: ^0.19.0
  get_it: ^7.2.0
  flutter_svg: ^2.0.10+1
  form_field_validator: ^1.1.0
  cached_network_image: ^3.2.0
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html_core: ^0.15.1
  animations: ^2.0.11
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0
  build_runner: ^2.4.10
  stacked_generator: ^1.6.1
  hive_generator: ^2.0.1


flutter:

 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/Illustration/
    - assets/flags/
    - assets/logo/
    - assets/screens/

  fonts:
    - family: Plus Jakarta
      fonts:
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Regular.otf
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Bold.otf
          weight: 700
    - family: Grandis Extended
      fonts:
        - asset: assets/fonts/grandis_extended/GrandisExtended-Regular.ttf
        - asset: assets/fonts/grandis_extended/GrandisExtended-Thin.ttf
          weight: 300
        - asset: assets/fonts/grandis_extended/GrandisExtended-Medium.ttf
          weight: 500
        - asset: assets/fonts/grandis_extended/GrandisExtended-Bold.ttf
          weight: 700
        - asset: assets/fonts/grandis_extended/GrandisExtended-Black.ttf
          weight: 900